//Localhost

### Get all contacts from localhost GET http://localhost:3000/contacts

### Get all contacts from localhost GET http://localhost:3000/contacts/contacts/662df7a08cd0402da79b8fee

//Production

### Get all contacts GET https://cse341-projects-vf7d.onrender.com/contacts

### Get contact by ID GET https://cse341-projects-vf7d.onrender.com/contacts/662df7a08cd0402da79b8fee


